### ISSUE TITLE
Formato de README

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105-huevos_rotos_con_jamon#2]
Usad formato markdown en README, tal y como se explica en esta [guía](https://github.com/aigora/punto_inicio/wiki/ANEXO:-C%C3%B3mo-dar-formato-al-texto-del-archivo-README.md.-Markdown). 

En particular, este texto debería usar "items" en lugar de ser un párrafo de frases contiguas:
> Planos: 5 pisos. edificios A, B y C. Registro: Mediante un cuadro de diálogo en el que se registrará mediante nombre, apellidos, clase, grupo y contraseña. Se le asignará su propio horario.(se realizará una base de datos en el que figuren los horarios). Horario: El programa tendrá un reloj asignado en función de la hora y el día de manera que sabrá decirle al alumno qué clase y dónde la tiene. También podrá ver la hora siguiente que le toca mientras aunque no haya terminado la clase anterior. Caminos:Se podrá elegir si la ruta se usarán atajos entre otras opciones. Base de datos: El programa guarda tu registro, con lo que la próxima vez que lo uses solo tendrás que decir tu nombre y una contraseña

**Comment by Juliauru** [comment]
Revisad el formato.
